FROM node:14
# set working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

ENV PATH /usr/src/app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY /spa/package.json /usr/src/app/package.json
RUN npm install --silent

# start app
CMD ["npm", "run", "start"]