# base image
FROM node:latest
# add dependencies so that we can build some native node_modules
#RUN apk --no-cache add --virtual native-deps \
#  g++ gcc libgcc libstdc++ linux-headers make python && \
#  npm install --quiet node-gyp -g &&\
#  npm install --quiet && \
#  apk del native-deps



# set working directory
RUN mkdir -p /usr/src/hyperbole-app
WORKDIR /usr/src/hyperbole-app

# add `/usr/src/hyperbole-app/node_modules/.bin` to $PATH
ENV PATH /usr/src/hyperbole-app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY /spa/package.json /usr/src/hyperbole-app/package.json
RUN npm install --silent

# start app
CMD ["npm", "run", "start"]